import type { DoseEntry } from "./RenalDosing";

// Additional medications across specialties for unified search:
// Hypertension, Lipids, Thyroid, Obesity, Anemia/Blood, Acid suppression.
// Source: KDIGO 2024, ADA 2026, ESC/AHA 2024, BNF, Lexicomp, Sandoz/UpToDate summaries.

export const ADDITIONAL_MEDS_DATA: DoseEntry[] = [
  // ═══════ ACE INHIBITORS ═══════
  {
    drug: "Ramipril",
    drugClass: "ACE Inhibitor",
    normalDose: "2.5–10 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment; monitor K⁺/Cr",
    eGFR30_44: "Start 1.25 mg/day; max 5 mg/day",
    eGFR15_29: "Start 1.25 mg/day; max 5 mg/day",
    eGFRBelow15: "Use with caution; reduce dose; monitor closely",
    notes: "Expect ≤30% Cr rise after initiation. Hold if K⁺ >5.5 or AKI.",
    hepatic: "No adjustment in mild–moderate. Severe impairment: use with caution — impaired prodrug activation.",
  },
  {
    drug: "Enalapril",
    drugClass: "ACE Inhibitor",
    normalDose: "5–40 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Start 2.5 mg/day",
    eGFR15_29: "Start 2.5 mg/day; max 20 mg/day",
    eGFRBelow15: "2.5 mg/day; titrate cautiously",
    notes: "Active metabolite enalaprilat renally cleared.",
    hepatic: "Severe impairment: impaired conversion to enalaprilat — use cautiously.",
  },
  {
    drug: "Lisinopril",
    drugClass: "ACE Inhibitor",
    normalDose: "10–40 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Start 5 mg/day",
    eGFR15_29: "Start 2.5–5 mg/day",
    eGFRBelow15: "Start 2.5 mg/day; titrate per BP/K⁺",
    notes: "Not hepatically metabolised — preferred ACEi in liver disease.",
    hepatic: "No adjustment — not metabolised by the liver.",
  },
  {
    drug: "Perindopril",
    drugClass: "ACE Inhibitor",
    normalDose: "4–8 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "2–4 mg/day",
    eGFR30_44: "2 mg/day",
    eGFR15_29: "2 mg every other day",
    eGFRBelow15: "Avoid or use under specialist supervision",
    notes: "",
    hepatic: "Severe: use with caution.",
  },

  // ═══════ DIRECT RENIN INHIBITOR ═══════
  {
    drug: "Aliskiren",
    drugClass: "Direct Renin Inhibitor",
    normalDose: "150–300 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Use with caution; monitor K⁺",
    eGFR15_29: "Avoid",
    eGFRBelow15: "Avoid",
    notes: "CONTRAINDICATED with ACEi/ARB in diabetes (ALTITUDE trial). Avoid in pregnancy, bilateral RAS, eGFR <30.获批用于高血压单药或与ACEi/ARB联合用于非糖尿病CKD。",
    hepatic: "No adjustment in mild–moderate. Severe: not recommended.",
  },

  // ═══════ NEWER / SPECIALTY AGENTS ═══════
  {
    drug: "Aprocitentan",
    drugClass: "Dual Endothelin Receptor Antagonist",
    normalDose: "12.5–25 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Use with caution; monitor for fluid retention",
    eGFR15_29: "Limited data; use with caution",
    eGFRBelow15: "Not recommended",
    notes: "FDA-approved for resistant HTN (PRECISION trial). Dual ETA/ETB antagonist. Common AE: edema/fluid retention (manage with diuretics), headache, nasal congestion. Monitor LFTs. Contraindicated in pregnancy (can cause fetal harm). Requires REMS program. Avoid cyclosporine.",
    hepatic: "Moderate impairment: max 12.5 mg/day. Severe: not recommended.",
  },
  {
    drug: "Baxdrostat",
    drugClass: "Aldosterone Synthase Inhibitor (Investigational)",
    normalDose: "1–2 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Use with caution; monitor K⁺",
    eGFR15_29: "Limited data",
    eGFRBelow15: "Not studied",
    notes: "Investigational (not yet FDA-approved). Highly selective aldosterone synthase (CYP11B2) inhibitor — suppresses aldosterone without affecting cortisol. Phase 2 BrigHTN trial: dose-dependent BP reduction in resistant HTN. AE: hyperkalemia (dose-dependent), hyponatremia. Monitor K⁺, Na⁺, cortisol.",
    hepatic: "No data; use with caution.",
  },

  // ═══════ ARBs ═══════
  {
    drug: "Losartan",
    drugClass: "ARB",
    normalDose: "50–100 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "Use with caution; monitor K⁺",
    eGFRBelow15: "Start low; monitor closely",
    notes: "Less cough than ACEi.",
    hepatic: "Child–Pugh B/C: start 25 mg/day — active metabolite formation reduced.",
  },
  {
    drug: "Telmisartan",
    drugClass: "ARB",
    normalDose: "40–80 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment (hepatic clearance)",
    eGFRBelow15: "No adjustment; monitor K⁺ in HD",
    notes: "Mostly biliary excretion — preferred ARB in CKD.",
    hepatic: "Mild–moderate: max 40 mg/day. Severe/biliary obstruction: contraindicated.",
  },
  {
    drug: "Valsartan",
    drugClass: "ARB",
    normalDose: "80–320 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "Use with caution",
    eGFRBelow15: "Use with caution; monitor K⁺",
    notes: "",
    hepatic: "Mild–moderate non-biliary: max 80 mg/day. Severe or biliary cirrhosis: contraindicated.",
  },
  {
    drug: "Olmesartan",
    drugClass: "ARB",
    normalDose: "20–40 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Max 20 mg/day",
    eGFR15_29: "Max 20 mg/day; use caution",
    eGFRBelow15: "Not recommended",
    notes: "Sprue-like enteropathy reported.",
    hepatic: "No specific adjustment; caution in severe disease.",
  },

  // ═══════ ARNI ═══════
  {
    drug: "Sacubitril-Valsartan",
    drugClass: "ARNI",
    normalDose: "49/51 mg BID → target 97/103 mg BID",
    eGFR60_89: "Standard",
    eGFR45_59: "Standard",
    eGFR30_44: "Start 24/26 mg BID",
    eGFR15_29: "Start 24/26 mg BID; titrate slowly",
    eGFRBelow15: "Not recommended — limited data",
    notes: "Wash out ACEi ≥36 h before starting. Monitor K⁺ and Cr.",
    hepatic: "Mild: no change. Moderate: start 24/26 mg BID. Severe (Child–Pugh C): not recommended.",
  },

  // ═══════ CCBs ═══════
  {
    drug: "Azelnidipine",
    drugClass: "Calcium Channel Blocker (DHP)",
    normalDose: "8–16 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment — hepatic clearance",
    notes: "Used in Asia (Japan, India). Long t½ (~19 h) — true OD dosing. Less peripheral oedema vs amlodipine. Also has some T-type calcium channel blocking effect.",
    hepatic: "Avoid in severe hepatic impairment — extensively hepatically metabolised via CYP3A4.",
  },
  {
    drug: "Amlodipine",
    drugClass: "Calcium Channel Blocker (DHP)",
    normalDose: "2.5–10 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment — non-renal clearance",
    notes: "Useful across all CKD stages; watch peripheral oedema.",
    hepatic: "Start 2.5 mg/day; titrate slowly — half-life prolonged.",
  },
  {
    drug: "Nifedipine",
    drugClass: "Calcium Channel Blocker (DHP)",
    normalDose: "30–90 mg/day (ER)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Use ER formulation; immediate-release linked to reflex tachycardia.",
    hepatic: "Reduce dose 50–60% in cirrhosis — high first-pass.",
  },
  {
    drug: "Diltiazem",
    drugClass: "Calcium Channel Blocker (non-DHP)",
    normalDose: "120–360 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "Use with caution",
    eGFRBelow15: "Use with caution; monitor HR/BP",
    notes: "Avoid with HFrEF.",
    hepatic: "Start low (e.g., 120 mg ER); titrate slowly. Severe: use with caution.",
  },
  {
    drug: "Verapamil",
    drugClass: "Calcium Channel Blocker (non-DHP)",
    normalDose: "120–480 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Reduce dose 25–50%",
    eGFR15_29: "Reduce dose 50%",
    eGFRBelow15: "Reduce dose 50–75%",
    notes: "Avoid with HFrEF or AV block.",
    hepatic: "Reduce dose by ~70% in cirrhosis — extensive first-pass.",
  },

  // ═══════ DIURETICS ═══════
  {
    drug: "Hydrochlorothiazide",
    drugClass: "Thiazide Diuretic",
    normalDose: "12.5–25 mg/day",
    eGFR60_89: "Effective",
    eGFR45_59: "Effective",
    eGFR30_44: "Reduced efficacy; consider higher dose or switch",
    eGFR15_29: "Generally ineffective — switch to loop",
    eGFRBelow15: "Ineffective — use loop diuretic",
    notes: "Combine with loop in refractory oedema.",
    hepatic: "Use cautiously — risk of hepatic encephalopathy with electrolyte shifts.",
  },
  {
    drug: "Chlorthalidone",
    drugClass: "Thiazide-like Diuretic",
    normalDose: "12.5–25 mg/day",
    eGFR60_89: "Effective",
    eGFR45_59: "Effective",
    eGFR30_44: "Still effective (CLICK trial up to eGFR 15–45)",
    eGFR15_29: "May still be effective per CLICK trial",
    eGFRBelow15: "Insufficient data; loop preferred",
    notes: "Longer t½ than HCTZ; greater BP reduction.",
    hepatic: "Use cautiously — risk of encephalopathy with electrolyte shifts.",
  },
  {
    drug: "Indapamide",
    drugClass: "Thiazide-like Diuretic",
    normalDose: "1.25–2.5 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Use with caution",
    eGFR15_29: "Avoid",
    eGFRBelow15: "Contraindicated",
    notes: "",
    hepatic: "Severe impairment: contraindicated — risk of hepatic encephalopathy.",
  },
  {
    drug: "Furosemide",
    drugClass: "Loop Diuretic",
    normalDose: "20–80 mg PO or IV",
    eGFR60_89: "Standard",
    eGFR45_59: "Standard",
    eGFR30_44: "Higher doses often needed",
    eGFR15_29: "May need 80–200 mg; consider IV/infusion",
    eGFRBelow15: "Doses up to 250–500 mg may be required",
    notes: "Tubular secretion required — diuretic resistance common in advanced CKD.",
    hepatic: "Use cautiously; risk of encephalopathy and hypokalaemia. Combine with K⁺-sparing agent.",
  },
  {
    drug: "Torsemide",
    drugClass: "Loop Diuretic",
    normalDose: "5–20 mg/day",
    eGFR60_89: "Standard",
    eGFR45_59: "Standard",
    eGFR30_44: "Often standard; longer t½ vs furosemide",
    eGFR15_29: "Higher doses may be needed",
    eGFRBelow15: "Higher doses may be needed",
    notes: "Better oral bioavailability than furosemide.",
    hepatic: "Use cautiously; risk of encephalopathy.",
  },
  {
    drug: "Bumetanide",
    drugClass: "Loop Diuretic",
    normalDose: "0.5–2 mg/day",
    eGFR60_89: "Standard",
    eGFR45_59: "Standard",
    eGFR30_44: "Standard; may need increase",
    eGFR15_29: "Higher doses required",
    eGFRBelow15: "Up to 10 mg/day may be required",
    notes: "1 mg ≈ 40 mg furosemide.",
    hepatic: "Use cautiously; encephalopathy risk.",
  },
  {
    drug: "Spironolactone",
    drugClass: "MRA / K⁺-sparing",
    normalDose: "12.5–50 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Use with caution; monitor K⁺",
    eGFR30_44: "Use with caution; monitor K⁺ closely",
    eGFR15_29: "Generally avoid — hyperkalaemia risk",
    eGFRBelow15: "Avoid",
    notes: "Stop if K⁺ >5.5 mmol/L.",
    hepatic: "Useful for ascites in cirrhosis (100–400 mg/day with furosemide).",
  },
  {
    drug: "Eplerenone",
    drugClass: "MRA",
    normalDose: "25–50 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Use with caution",
    eGFR30_44: "Reduce dose; monitor K⁺",
    eGFR15_29: "Avoid",
    eGFRBelow15: "Contraindicated",
    notes: "",
    hepatic: "Mild–moderate: no adjustment. Severe: not studied.",
  },
  {
    drug: "Finerenone",
    drugClass: "Non-steroidal MRA",
    normalDose: "10–20 mg/day",
    eGFR60_89: "20 mg/day",
    eGFR45_59: "20 mg/day",
    eGFR30_44: "10 mg/day; titrate based on K⁺",
    eGFR15_29: "10 mg/day if K⁺ ≤5.0; do not initiate if eGFR <25",
    eGFRBelow15: "Not recommended",
    notes: "FIDELIO/FIGARO — renoprotection in T2DM CKD.",
    hepatic: "Severe (Child–Pugh C): avoid.",
  },

  // ═══════ BETA-BLOCKERS ═══════
  {
    drug: "Metoprolol",
    drugClass: "Beta-Blocker (β1)",
    normalDose: "25–200 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment — hepatic clearance",
    notes: "Preferred BB in CKD.",
    hepatic: "Reduce dose in severe impairment; start low.",
  },
  {
    drug: "Bisoprolol",
    drugClass: "Beta-Blocker (β1)",
    normalDose: "2.5–10 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Max 10 mg/day",
    eGFR15_29: "Start 2.5 mg/day; max 10 mg/day",
    eGFRBelow15: "Start 2.5 mg/day; titrate cautiously",
    notes: "50% renal / 50% hepatic clearance.",
    hepatic: "Severe: start 2.5 mg/day; max 10 mg/day.",
  },
  {
    drug: "Carvedilol",
    drugClass: "Combined α/β-blocker",
    normalDose: "3.125–25 mg BID",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Preferred in HFrEF; not removed by dialysis.",
    hepatic: "Severe impairment (Child–Pugh C): contraindicated.",
  },
  {
    drug: "Atenolol",
    drugClass: "Beta-Blocker (β1)",
    normalDose: "25–100 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Max 50 mg/day",
    eGFR15_29: "25 mg/day or every other day",
    eGFRBelow15: "25 mg every 2–3 days; supplement after HD",
    notes: "Renally excreted — accumulates in CKD.",
    hepatic: "No adjustment.",
  },
  {
    drug: "Nebivolol",
    drugClass: "Beta-Blocker (vasodilating)",
    normalDose: "2.5–10 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Start at 2.5 mg",
    eGFR15_29: "Start at 2.5 mg",
    eGFRBelow15: "Limited data",
    notes: "3rd-gen β₁-selective blocker with NO-mediated vasodilation. Hepatic metabolism (CYP2D6). Active metabolites accumulate in CKD — start low. Reduces oxidative stress and improves endothelial function. Preferred β-blocker in CKD with metabolic syndrome.",
    hepatic: "Severe: use with caution — CYP2D6 dependent.",
  },
  {
    drug: "Labetalol",
    drugClass: "Beta-Blocker (α/β)",
    normalDose: "100–400 mg BID PO; 20 mg IV bolus",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Preferred in pregnancy and hypertensive urgency.",
    hepatic: "Use with caution; reduce dose — extensive first-pass.",
  },

  // ═══════ CENTRAL / OTHER ANTIHYPERTENSIVES ═══════
  {
    drug: "Clonidine",
    drugClass: "Central α2-agonist",
    normalDose: "0.1–0.3 mg BID",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Reduce dose; titrate slowly",
    eGFR15_29: "Reduce dose 50%",
    eGFRBelow15: "Reduce dose 50–75%",
    notes: "Rebound hypertension if abruptly stopped.",
    hepatic: "No specific adjustment.",
  },
  {
    drug: "Moxonidine",
    drugClass: "Central α2-agonist",
    normalDose: "0.2–0.4 mg OD",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Use with caution",
    eGFR15_29: "Reduce dose 50%",
    eGFRBelow15: "Limited data; use with caution",
    notes: "Imidazoline receptor agonist. Less sedation than clonidine. Start 0.2 mg OD, max 0.6 mg/day. No rebound on withdrawal vs clonidine. Preferred central agent in CKD due to lower adverse effect profile.",
    hepatic: "No specific adjustment.",
  },
  {
    drug: "Hydralazine",
    drugClass: "Direct Vasodilator",
    normalDose: "25–100 mg q6–8h",
    eGFR60_89: "q8h",
    eGFR45_59: "q8h",
    eGFR30_44: "q8h",
    eGFR15_29: "q8–12h",
    eGFRBelow15: "q12–24h",
    notes: "Drug-induced lupus with prolonged high-dose use.",
    hepatic: "Reduce dose in severe impairment.",
  },
  {
    drug: "Prazosin",
    drugClass: "α1-Blocker",
    normalDose: "1–10 mg BID–TID",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Start 0.5 mg",
    eGFR15_29: "Start 0.5 mg",
    eGFRBelow15: "Start 0.5 mg",
    notes: "First-dose hypotension — start at bedtime.",
    hepatic: "Start low; titrate slowly.",
  },
  {
    drug: "Doxazosin",
    drugClass: "α1-Blocker",
    normalDose: "1–8 mg OD",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Start 1 mg",
    eGFR15_29: "Use with caution",
    eGFRBelow15: "Use with caution; limited data",
    notes: "Longer T½ than prazosin — true OD dosing. ALLHAT trial: increased HF vs chlorthalidone — no longer 1st-line HTN monotherapy. Also used for BPH. First-dose syncope risk — start 1 mg at bedtime.",
    hepatic: "Use with caution in severe impairment.",
  },
  {
    drug: "Atorvastatin",
    drugClass: "Statin (HMG-CoA reductase inhibitor)",
    normalDose: "10–80 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment (preferred statin in advanced CKD/HD)",
    notes: "Hepatically cleared — first-line statin in CKD.",
    hepatic: "Active liver disease or persistent ALT >3× ULN: contraindicated.",
  },
  {
    drug: "Rosuvastatin",
    drugClass: "Statin (HMG-CoA reductase inhibitor)",
    normalDose: "5–40 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Max 10 mg/day",
    eGFR15_29: "Start 5 mg/day; max 10 mg/day",
    eGFRBelow15: "Max 10 mg/day; avoid 40 mg",
    notes: "Asian patients: start 5 mg/day.",
    hepatic: "Active liver disease or unexplained ALT ↑: contraindicated.",
  },
  {
    drug: "Simvastatin",
    drugClass: "Statin",
    normalDose: "10–40 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Start 5 mg/day",
    eGFR15_29: "Start 5 mg/day; max 20 mg/day",
    eGFRBelow15: "Start 5 mg/day; max 20 mg/day",
    notes: "Multiple CYP3A4 interactions — avoid 80 mg.",
    hepatic: "Active liver disease: contraindicated.",
  },
  {
    drug: "Pravastatin",
    drugClass: "Statin",
    normalDose: "10–80 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Start 10 mg/day",
    eGFR15_29: "Start 10 mg/day",
    eGFRBelow15: "Start 10 mg/day; max 40 mg/day",
    notes: "Hydrophilic — fewer drug interactions.",
    hepatic: "Active liver disease: contraindicated.",
  },
  {
    drug: "Pitavastatin",
    drugClass: "Statin",
    normalDose: "1–4 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Max 2 mg/day",
    eGFR30_44: "Max 2 mg/day",
    eGFR15_29: "Max 2 mg/day",
    eGFRBelow15: "Max 2 mg/day (HD)",
    notes: "Minimal CYP metabolism.",
    hepatic: "Active liver disease: contraindicated.",
  },

  // ═══════ NON-STATIN LIPID DRUGS ═══════
  {
    drug: "Ezetimibe",
    drugClass: "Cholesterol Absorption Inhibitor",
    normalDose: "10 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Often combined with statin.",
    hepatic: "Moderate–severe (Child–Pugh B/C): not recommended.",
  },
  {
    drug: "Bempedoic Acid",
    drugClass: "ATP-citrate Lyase Inhibitor",
    normalDose: "180 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "Limited data",
    eGFRBelow15: "Limited data; not recommended in HD",
    notes: "↑ uric acid and gout risk.",
    hepatic: "Severe: not studied — avoid.",
  },
  {
    drug: "Fenofibrate",
    drugClass: "Fibrate",
    normalDose: "145 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "48 mg/day",
    eGFR30_44: "48 mg/day",
    eGFR15_29: "Avoid",
    eGFRBelow15: "Contraindicated",
    notes: "Reversible ↑ Cr; avoid with statin in CKD if possible.",
    hepatic: "Active liver disease: contraindicated.",
  },
  {
    drug: "Gemfibrozil",
    drugClass: "Fibrate",
    normalDose: "600 mg BID",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Use with caution",
    eGFR30_44: "Avoid",
    eGFR15_29: "Contraindicated",
    eGFRBelow15: "Contraindicated",
    notes: "Do NOT combine with statins (myopathy risk).",
    hepatic: "Severe/biliary cirrhosis: contraindicated.",
  },
  {
    drug: "Evolocumab",
    drugClass: "PCSK9 Inhibitor",
    normalDose: "140 mg SC q2w or 420 mg q4w",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment; limited HD data",
    notes: "Monoclonal antibody — non-renal clearance.",
    hepatic: "Severe (Child–Pugh C): not studied.",
  },
  {
    drug: "Alirocumab",
    drugClass: "PCSK9 Inhibitor",
    normalDose: "75–150 mg SC q2w",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment; limited HD data",
    notes: "",
    hepatic: "Severe: not studied.",
  },
  {
    drug: "Icosapent Ethyl",
    drugClass: "Omega-3 Fatty Acid (EPA)",
    normalDose: "2 g BID",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "REDUCE-IT — CV benefit; ↑ AF risk.",
    hepatic: "Monitor LFTs in hepatic impairment.",
  },

  // ═══════ THYROID ═══════
  {
    drug: "Levothyroxine",
    drugClass: "Thyroid Hormone (T4)",
    normalDose: "1.6 µg/kg/day (full replacement)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment — titrate to TSH",
    notes: "Empty stomach, 30–60 min before food. Avoid Ca/Fe/PPI co-administration.",
    hepatic: "No specific adjustment — titrate to TSH.",
  },
  {
    drug: "Liothyronine",
    drugClass: "Thyroid Hormone (T3)",
    normalDose: "25–75 µg/day in divided doses",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Start low in cardiac disease (5 µg/day).",
    hepatic: "No specific adjustment; monitor.",
  },
  {
    drug: "Carbimazole",
    drugClass: "Antithyroid (thionamide)",
    normalDose: "15–40 mg/day → 5–15 mg maintenance",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Reduce dose ~25%",
    eGFR15_29: "Reduce dose ~50%",
    eGFRBelow15: "Reduce dose ~50%",
    notes: "Agranulocytosis warning — check FBC if febrile/sore throat.",
    hepatic: "Cholestatic hepatitis risk; avoid in severe hepatic disease.",
  },
  {
    drug: "Methimazole",
    drugClass: "Antithyroid (thionamide)",
    normalDose: "5–30 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "Use with caution",
    eGFRBelow15: "Use with caution",
    notes: "Preferred over PTU except 1st trimester or thyroid storm.",
    hepatic: "Stop if ALT >3× ULN; avoid in severe disease.",
  },
  {
    drug: "Propylthiouracil",
    drugClass: "Antithyroid (thionamide)",
    normalDose: "100 mg q8h (300 mg/day)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Reduce dose ~25%",
    eGFR15_29: "Reduce dose ~50%",
    eGFRBelow15: "Reduce dose ~50%",
    notes: "Preferred in 1st trimester pregnancy and thyroid storm.",
    hepatic: "Boxed warning: severe hepatotoxicity — avoid in liver disease.",
  },

  // ═══════ ANTI-OBESITY ═══════
  {
    drug: "Orlistat",
    drugClass: "Anti-obesity (lipase inhibitor)",
    normalDose: "120 mg TID with meals",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Use with caution — oxalate nephropathy risk",
    eGFR15_29: "Avoid — oxalate nephropathy",
    eGFRBelow15: "Avoid",
    notes: "Supplement fat-soluble vitamins (A, D, E, K) at bedtime.",
    hepatic: "Cholestasis: contraindicated. Rare severe liver injury reported.",
  },
  {
    drug: "Liraglutide (Saxenda)",
    drugClass: "GLP-1 RA (anti-obesity)",
    normalDose: "0.6 mg/day → titrate to 3.0 mg SC daily",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Use with caution; limited data",
    eGFR15_29: "Use with caution; limited data",
    eGFRBelow15: "Not recommended (incl. dialysis)",
    notes: "Titrate weekly to reduce GI side effects.",
    hepatic: "Limited data in severe hepatic impairment — use with caution.",
  },
  {
    drug: "Semaglutide (Wegovy)",
    drugClass: "GLP-1 RA (anti-obesity)",
    normalDose: "0.25 mg → titrate to 2.4 mg SC weekly",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment; monitor hydration",
    eGFRBelow15: "Limited data; use with caution",
    notes: "STEP trials — 15–17% weight loss.",
    hepatic: "No specific adjustment; limited data in severe impairment.",
  },
  {
    drug: "Tirzepatide (Zepbound)",
    drugClass: "GIP/GLP-1 dual agonist (anti-obesity)",
    normalDose: "2.5 mg → titrate to 15 mg SC weekly",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment; monitor hydration",
    eGFRBelow15: "Limited data",
    notes: "SURMOUNT — 20–22% weight loss.",
    hepatic: "No adjustment; limited data in severe disease.",
  },
  {
    drug: "Naltrexone-Bupropion",
    drugClass: "Anti-obesity (combination)",
    normalDose: "16/180 mg BID (titrated over 4 wk)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Max 8/90 mg BID",
    eGFR30_44: "Max 8/90 mg BID",
    eGFR15_29: "Not recommended",
    eGFRBelow15: "Contraindicated",
    notes: "Contraindicated with uncontrolled HTN, seizures, opioid use.",
    hepatic: "Hepatic impairment: max 8/90 mg AM only. Severe: contraindicated.",
  },
  {
    drug: "Phentermine-Topiramate",
    drugClass: "Anti-obesity (combination)",
    normalDose: "7.5/46 mg/day; max 15/92 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Max 7.5/46 mg/day",
    eGFR30_44: "Max 7.5/46 mg/day",
    eGFR15_29: "Not recommended",
    eGFRBelow15: "Contraindicated",
    notes: "REMS programme; teratogenic.",
    hepatic: "Moderate: max 7.5/46 mg/day. Severe: not studied — avoid.",
  },

  // ═══════ ANEMIA / BLOOD ═══════
  {
    drug: "Ferrous Sulfate",
    drugClass: "Oral Iron",
    normalDose: "65 mg elemental Fe OD–TID (or alternate-day)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Often inadequate in CKD — consider IV iron",
    eGFR15_29: "IV iron preferred",
    eGFRBelow15: "IV iron preferred (esp. on HD)",
    notes: "Alternate-day dosing ↑ absorption, ↓ GI side effects.",
    hepatic: "Avoid in haemochromatosis; otherwise no adjustment.",
  },
  {
    drug: "Ferric Carboxymaltose",
    drugClass: "IV Iron",
    normalDose: "750–1000 mg IV (max 1500 mg/wk)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment — preferred route in CKD",
    eGFRBelow15: "No adjustment; safe in HD",
    notes: "Hypophosphataemia risk — monitor PO₄ after repeated doses.",
    hepatic: "Avoid in decompensated liver disease.",
  },
  {
    drug: "Iron Sucrose",
    drugClass: "IV Iron",
    normalDose: "100–200 mg IV per session (HD)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "Standard CKD dosing",
    eGFRBelow15: "Standard HD dosing",
    notes: "Lower single-dose ceiling than FCM.",
    hepatic: "Caution in decompensated liver disease.",
  },
  {
    drug: "Erythropoietin alfa",
    drugClass: "ESA",
    normalDose: "50–100 U/kg SC 3×/wk",
    eGFR60_89: "Initiate if Hb <10 g/dL in CKD",
    eGFR45_59: "Per Hb target 10–11.5 g/dL",
    eGFR30_44: "Per Hb target",
    eGFR15_29: "Per Hb target",
    eGFRBelow15: "Per Hb target (HD)",
    notes: "Ensure iron repletion first (TSAT >20%, ferritin >100).",
    hepatic: "No specific adjustment.",
  },
  {
    drug: "Darbepoetin alfa",
    drugClass: "ESA (long-acting)",
    normalDose: "0.45 µg/kg SC weekly or 0.75 µg/kg q2w",
    eGFR60_89: "Per Hb target",
    eGFR45_59: "Per Hb target",
    eGFR30_44: "Per Hb target",
    eGFR15_29: "Per Hb target",
    eGFRBelow15: "Per Hb target",
    notes: "Longer t½; convert from epoetin by ratio.",
    hepatic: "No specific adjustment.",
  },
  {
    drug: "Folic Acid",
    drugClass: "Vitamin",
    normalDose: "1–5 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment (may need 1 mg/day in HD)",
    notes: "Always assess B12 before treating macrocytic anaemia.",
    hepatic: "No adjustment.",
  },
  {
    drug: "Cyanocobalamin (B12)",
    drugClass: "Vitamin",
    normalDose: "1000 µg IM weekly ×4–6 then monthly",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Oral 1–2 mg/day equivalent for most causes.",
    hepatic: "No adjustment.",
  },

  // ═══════ ANTIPLATELET (cardio) ═══════
  {
    drug: "Aspirin",
    drugClass: "Antiplatelet",
    normalDose: "75–100 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "Use with caution — bleeding risk ↑",
    eGFRBelow15: "Use with caution",
    notes: "Reassess benefit vs bleeding in advanced CKD.",
    hepatic: "Severe hepatic disease/coagulopathy: avoid.",
  },
  {
    drug: "Clopidogrel",
    drugClass: "Antiplatelet (P2Y12)",
    normalDose: "75 mg/day (300–600 mg load)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "CYP2C19 poor metabolisers — consider ticagrelor/prasugrel.",
    hepatic: "Severe: use with caution — limited data.",
  },
  {
    drug: "Ticagrelor",
    drugClass: "Antiplatelet (P2Y12)",
    normalDose: "90 mg BID (60 mg BID after 12 mo)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "Limited data; use with caution",
    notes: "Dyspnoea common; avoid with strong CYP3A4 inhibitors.",
    hepatic: "Severe: contraindicated.",
  },

  // ═══════ ACID SUPPRESSION (commonly missed) ═══════
  {
    drug: "Omeprazole",
    drugClass: "Proton Pump Inhibitor",
    normalDose: "20–40 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Long-term use linked to hypomagnesaemia & ↓ B12 absorption.",
    hepatic: "Severe: max 20 mg/day.",
  },
  {
    drug: "Pantoprazole",
    drugClass: "Proton Pump Inhibitor",
    normalDose: "40 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Preferred PPI with clopidogrel (less CYP2C19 interaction).",
    hepatic: "Severe: max 40 mg/day; monitor LFTs.",
  },
  {
    drug: "Ranitidine",
    drugClass: "H2 Receptor Antagonist",
    normalDose: "150 mg BID",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "150 mg/day",
    eGFR15_29: "150 mg every other day",
    eGFRBelow15: "150 mg every 2–3 days",
    notes: "Withdrawn in many markets due to NDMA contamination — use famotidine.",
    hepatic: "Reduce dose in severe hepatic impairment.",
  },
  {
    drug: "Famotidine",
    drugClass: "H2 Receptor Antagonist",
    normalDose: "20–40 mg/day",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "20 mg/day",
    eGFR15_29: "20 mg every other day",
    eGFRBelow15: "20 mg every 2–3 days",
    notes: "Preferred H2RA post-ranitidine withdrawal.",
    hepatic: "No specific adjustment.",
  },
  // ═══════ INSULINS ═══════
  {
    drug: "Insulin Glargine (U-100)",
    drugClass: "Long-acting basal insulin",
    normalDose: "0.1–0.2 U/kg SC OD (starting); titrate to FBG target",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce dose ~25%; monitor closely",
    eGFR30_44: "Reduce dose ~25%; monitor closely",
    eGFR15_29: "Reduce dose ~50%; ↑ hypoglycemia risk",
    eGFRBelow15: "Reduce dose ~50%; individualize, frequent SMBG",
    notes: "Peakless 24h basal. Insulin requirements ↓ in CKD due to ↓ renal clearance and ↓ gluconeogenesis.",
    hepatic: "Reduce dose; impaired gluconeogenesis ↑ hypoglycemia risk. Titrate carefully.",
  },
  {
    drug: "Insulin Glargine U-300 (Toujeo)",
    drugClass: "Long-acting basal insulin",
    normalDose: "0.2 U/kg SC OD",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%; individualize",
    notes: "Flatter, longer (>24h) profile than U-100; lower nocturnal hypo risk.",
    hepatic: "Reduce dose; monitor closely.",
  },
  {
    drug: "Insulin Degludec",
    drugClass: "Ultra-long-acting basal insulin",
    normalDose: "0.1–0.2 U/kg SC OD (any time)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%; individualize",
    notes: "Duration >42h. Lowest hypoglycemia risk among basal insulins (DEVOTE).",
    hepatic: "Monitor; dose reduction often required.",
  },
  {
    drug: "Insulin Detemir",
    drugClass: "Long-acting basal insulin",
    normalDose: "0.1–0.2 U/kg SC OD or BID",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%",
    notes: "Often requires BID dosing. Less weight gain than glargine.",
    hepatic: "Reduce dose; monitor.",
  },
  {
    drug: "NPH Insulin (Isophane)",
    drugClass: "Intermediate-acting insulin",
    normalDose: "0.1–0.2 U/kg SC BID",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%; high nocturnal hypo risk",
    notes: "Peak 4–10h, duration 10–16h. Cheaper but ↑ hypoglycemia risk vs analog basals.",
    hepatic: "Reduce dose; monitor.",
  },
  {
    drug: "Insulin Lispro",
    drugClass: "Rapid-acting prandial insulin",
    normalDose: "0.05–0.1 U/kg per meal SC (or per ICR/CF)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%; individualize per SMBG/CGM",
    notes: "Onset 10–15 min, peak 1–2h, duration 3–5h. Inject 0–15 min before meals.",
    hepatic: "Reduce dose; monitor closely.",
  },
  {
    drug: "Insulin Aspart",
    drugClass: "Rapid-acting prandial insulin",
    normalDose: "0.05–0.1 U/kg per meal SC",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%",
    notes: "Faster aspart (Fiasp): even quicker onset. Use with meals.",
    hepatic: "Reduce dose; monitor.",
  },
  {
    drug: "Insulin Glulisine",
    drugClass: "Rapid-acting prandial insulin",
    normalDose: "0.05–0.1 U/kg per meal SC",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%",
    notes: "Onset ~15 min. Inject within 15 min before or 20 min after meal start.",
    hepatic: "Reduce dose; monitor.",
  },
  {
    drug: "Regular Insulin (Human)",
    drugClass: "Short-acting insulin",
    normalDose: "0.05–0.1 U/kg per meal SC; IV infusion for DKA/HHS",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%; high hypo risk",
    notes: "Onset 30 min, peak 2–4h, duration 5–8h. Inject 30 min pre-meal. Preferred IV for DKA/HHS and sliding scale.",
    hepatic: "Reduce dose; monitor closely.",
  },
  {
    drug: "Premixed Insulin 70/30 (NPH/Regular)",
    drugClass: "Premixed insulin",
    normalDose: "0.3–0.5 U/kg/day SC divided BID (2/3 AM, 1/3 PM, pre-meal)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%; individualize",
    notes: "Fixed ratio limits flexibility; useful when adherence to MDI is poor.",
    hepatic: "Reduce dose; monitor.",
  },
  {
    drug: "Premixed Insulin 75/25 or 70/30 (Analog: Lispro Mix / Aspart Mix)",
    drugClass: "Premixed analog insulin",
    normalDose: "0.3–0.5 U/kg/day SC divided BID with meals",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%",
    notes: "Faster onset than human premix; inject immediately before meals.",
    hepatic: "Reduce dose; monitor.",
  },
  {
    drug: "Insulin Degludec/Aspart (Ryzodeg 70/30)",
    drugClass: "Co-formulated basal + rapid analog",
    normalDose: "0.3–0.5 U/kg/day SC with main meal(s)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%",
    notes: "True co-formulation (not mixed suspension); flexible meal timing.",
    hepatic: "Reduce dose; monitor.",
  },
  {
    drug: "U-500 Regular Insulin (Concentrated)",
    drugClass: "Concentrated short-acting insulin",
    normalDose: "Reserved for severe insulin resistance (>200 U/day); BID–TID SC pre-meal",
    eGFR60_89: "No adjustment",
    eGFR45_59: "Reduce ~25%",
    eGFR30_44: "Reduce ~25%",
    eGFR15_29: "Reduce ~50%",
    eGFRBelow15: "Reduce ~50%",
    notes: "5× concentrated. Acts more like intermediate insulin (peak 4–8h). Dispense via dedicated U-500 syringe/pen to avoid dosing errors.",
    hepatic: "Reduce dose; monitor.",
  },
];
