import type { DoseEntry } from "./RenalDosing";

export const ANTIBIOTICS_DATA: DoseEntry[] = [
  // ── Penicillins ──
  {
    drug: "Amoxicillin",
    drugClass: "Penicillin",
    normalDose: "250–500 mg q8h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "250–500 mg q8h",
    eGFR15_29: "250–500 mg q8–12h",
    eGFRBelow15: "250–500 mg q12–24h",
    notes: "Renally excreted. Reduce frequency with declining GFR.",
  },
  {
    drug: "Amoxicillin-Clavulanate",
    drugClass: "Penicillin",
    normalDose: "625 mg q8h or 1 g q12h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "625 mg q12h",
    eGFR15_29: "625 mg q24h",
    eGFRBelow15: "Avoid (625 mg q24h max); risk of seizures with clavulanate accumulation",
    notes: "Clavulanate accumulates in renal failure. Monitor for neurotoxicity.",
  },
  {
    drug: "Piperacillin-Tazobactam",
    drugClass: "Penicillin",
    normalDose: "4.5 g q6–8h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "4.5 g q8h",
    eGFR30_44: "4.5 g q8h",
    eGFR15_29: "2.25 g q8h or 4.5 g q12h",
    eGFRBelow15: "2.25 g q8h or 4.5 g q12h",
    notes: "Extended infusion (4 h) preferred in critically ill with low eGFR.",
  },
  {
    drug: "Ampicillin",
    drugClass: "Penicillin",
    normalDose: "1–2 g q4–6h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "1–2 g q6h",
    eGFR30_44: "1–2 g q8h",
    eGFR15_29: "1–2 g q12h",
    eGFRBelow15: "1–2 g q12–24h",
    notes: "High-dose IV. Reduce frequency in advanced CKD.",
  },
  // ── Cephalosporins ──
  {
    drug: "Cephalexin",
    drugClass: "Cephalosporin (1st gen)",
    normalDose: "250–500 mg q6h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "250–500 mg q8h",
    eGFR15_29: "250–500 mg q12h",
    eGFRBelow15: "250–500 mg q24h",
    notes: "Common oral cephalosporin. Dosing interval increases as eGFR declines.",
  },
  {
    drug: "Cefazolin",
    drugClass: "Cephalosporin (1st gen)",
    normalDose: "1–2 g q8h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "1–2 g q12h",
    eGFR30_44: "1–2 g q12h",
    eGFR15_29: "1–2 g q24h",
    eGFRBelow15: "1–2 g q24–48h",
    notes: "Surgical prophylaxis. Must re-dose after dialysis.",
  },
  {
    drug: "Cefuroxime",
    drugClass: "Cephalosporin (2nd gen)",
    normalDose: "750 mg–1.5 g q8h (IV); 250–500 mg q12h (oral)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "750 mg–1.5 g q12h",
    eGFR15_29: "750 mg–1.5 g q24h",
    eGFRBelow15: "750 mg–1.5 g q24h",
    notes: "Reduce frequency for CrCl <30.",
  },
  {
    drug: "Ceftriaxone",
    drugClass: "Cephalosporin (3rd gen)",
    normalDose: "1–2 g q12–24h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Dual hepatic & renal clearance — generally safe across all CKD stages. Monitor for biliary sludging at high doses.",
  },
  {
    drug: "Ceftazidime",
    drugClass: "Cephalosporin (3rd gen)",
    normalDose: "1–2 g q8h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "1–2 g q12h",
    eGFR30_44: "1–2 g q12h",
    eGFR15_29: "1–2 g q24h",
    eGFRBelow15: "500 mg–1 g q24h or 1–2 g q48h",
    notes: "Primarily renal clearance. Significant dose reduction needed. Pseudo-CKD dosing: 500 mg q24h in ESRD.",
  },
  {
    drug: "Cefepime",
    drugClass: "Cephalosporin (4th gen)",
    normalDose: "1–2 g q8–12h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "1–2 g q12h",
    eGFR30_44: "1–2 g q12–24h",
    eGFR15_29: "500 mg–1 g q24h",
    eGFRBelow15: "250–500 mg q24h",
    notes: "Neurotoxic at high doses in CKD (myoclonus, encephalopathy). Dose carefully.",
  },
  {
    drug: "Cefixime",
    drugClass: "Cephalosporin (3rd gen)",
    normalDose: "200–400 mg q12h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "200–400 mg q24h",
    eGFR15_29: "200–400 mg q24h",
    eGFRBelow15: "200 mg q24h",
    notes: "Oral cephalosporin. Reduce dose by 50% if CrCl <30.",
  },
  // ── Carbapenems ──
  {
    drug: "Meropenem",
    drugClass: "Carbapenem",
    normalDose: "500 mg–1 g q8h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "500 mg–1 g q8–12h",
    eGFR30_44: "500 mg–1 g q12h",
    eGFR15_29: "250–500 mg q12h",
    eGFRBelow15: "250–500 mg q24h",
    notes: "Extended infusion (3 h) for resistant organisms. Adjust dosing interval.",
  },
  {
    drug: "Imipenem-Cilastatin",
    drugClass: "Carbapenem",
    normalDose: "500 mg q6h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "500 mg q6–8h",
    eGFR30_44: "500 mg q8–12h",
    eGFR15_29: "250–500 mg q12h",
    eGFRBelow15: "Avoid (risk of seizures with cilastatin accumulation)",
    notes: "Higher seizure risk vs meropenem in CKD. Prefer meropenem in renal impairment.",
  },
  {
    drug: "Ertapenem",
    drugClass: "Carbapenem",
    normalDose: "1 g q24h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "500 mg q24h",
    eGFR15_29: "500 mg q24h",
    eGFRBelow15: "500 mg q24h",
    notes: "Once-daily dosing. Dose reduction needed for CrCl <30.",
  },
  // ── Fluoroquinolones ──
  {
    drug: "Ciprofloxacin",
    drugClass: "Fluoroquinolone",
    normalDose: "250–750 mg q12h (oral); 200–400 mg q12h (IV)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "50–75% of normal dose q12h",
    eGFR15_29: "50% of normal dose q12h",
    eGFRBelow15: "50% of normal dose q12–24h",
    notes: "Renal and non-renal clearance. Reduce dose if CrCl <30. Avoid in elderly (tendon rupture risk).",
  },
  {
    drug: "Levofloxacin",
    drugClass: "Fluoroquinolone",
    normalDose: "250–750 mg q24h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "250–750 mg q48h",
    eGFR15_29: "250 mg q48h",
    eGFRBelow15: "250 mg q48h",
    notes: "Primarily renal clearance. Reduce frequency. Extended dosing interval in CKD.",
  },
  {
    drug: "Moxifloxacin",
    drugClass: "Fluoroquinolone",
    normalDose: "400 mg q24h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Hepatic clearance — no renal adjustment needed. Avoid in hepatic impairment. QT prolongation risk.",
  },
  // ── Aminoglycosides ──
  {
    drug: "Gentamicin",
    drugClass: "Aminoglycoside",
    normalDose: "3–5 mg/kg q24h (conventional) or 5–7 mg/kg (extended interval)",
    eGFR60_89: "Extended interval (q24h) preferred",
    eGFR45_59: "Extended interval (q36h) preferred",
    eGFR30_44: "Conventional dosing q24h or extended q48h",
    eGFR15_29: "Conventional q24–48h with TDM",
    eGFRBelow15: "Conventional q48h+ with TDM; dose post-dialysis",
    notes: "Nephrotoxic and ototoxic. Therapeutic drug monitoring (TDM) essential in all CKD stages. Extended-interval dosing preferred when feasible.",
  },
  {
    drug: "Amikacin",
    drugClass: "Aminoglycoside",
    normalDose: "15 mg/kg q24h",
    eGFR60_89: "Extended interval (q24h) preferred",
    eGFR45_59: "15 mg/kg q36h",
    eGFR30_44: "15 mg/kg q48h",
    eGFR15_29: "7.5 mg/kg q48h with TDM",
    eGFRBelow15: "7.5 mg/kg q48–72h with TDM; dose post-dialysis",
    notes: "Nephrotoxic. Monitor peak/trough. Extended interval in early CKD. Avoid or monitor closely with other nephrotoxins.",
  },
  // ── Glycopeptides ──
  {
    drug: "Vancomycin",
    drugClass: "Glycopeptide",
    normalDose: "15–20 mg/kg q8–12h (IV)",
    eGFR60_89: "15–20 mg/kg q12h",
    eGFR45_59: "15–20 mg/kg q12–24h",
    eGFR30_44: "15–20 mg/kg q24–48h",
    eGFR15_29: "15–20 mg/kg q48–96h",
    eGFRBelow15: "Loading dose 20–25 mg/kg, then 15 mg/kg q48–96h; monitor trough (15–20 mcg/mL)",
    notes: "Nephrotoxic at high troughs. Trough monitoring mandatory. AUC-guided dosing preferred. Acute kidney injury risk.",
  },
  {
    drug: "Teicoplanin",
    drugClass: "Glycopeptide",
    normalDose: "Loading 400–800 mg q12h × 3–5 doses, then 400 mg q24h",
    eGFR60_89: "400 mg q24h",
    eGFR45_59: "400 mg q24h",
    eGFR30_44: "400 mg q48h",
    eGFR15_29: "400 mg q72h",
    eGFRBelow15: "400 mg q72h; administer post-dialysis",
    notes: "Long half-life in CKD. TDM recommended (trough 10–20 mcg/mL, 15–30 for serious infections).",
  },
  // ── Lipopeptides ──
  {
    drug: "Daptomycin",
    drugClass: "Lipopeptide",
    normalDose: "4–6 mg/kg q24h (IV)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "4–6 mg/kg q24h",
    eGFR30_44: "4–6 mg/kg q48h",
    eGFR15_29: "4–6 mg/kg q48h",
    eGFRBelow15: "4–6 mg/kg q48h",
    notes: "Renally excreted. Extended dosing interval for CrCl <30. Monitor CPK (myopathy risk).",
  },
  // ── Oxazolidinones ──
  {
    drug: "Linezolid",
    drugClass: "Oxazolidinone",
    normalDose: "600 mg q12h (oral/IV)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Hepatic clearance — no renal adjustment. Metabolites accumulate in ESRD (significance unclear). Monitor platelets weekly.",
  },
  // ── Lincosamides ──
  {
    drug: "Clindamycin",
    drugClass: "Lincosamide",
    normalDose: "300–600 mg q6–8h (oral/IV)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Hepatic clearance — no renal dose adjustment. Risk of C. difficile colitis.",
  },
  // ── Nitroimidazoles ──
  {
    drug: "Metronidazole",
    drugClass: "Nitroimidazole",
    normalDose: "500 mg q8h (IV/oral)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment (reduce dose if hepatic impairment)",
    notes: "Hepatic clearance — no renal adjustment. Metabolites accumulate in ESRD but not clinically significant.",
  },
  // ── Sulfonamides ──
  {
    drug: "Trimethoprim-Sulfamethoxazole (TMP-SMX)",
    drugClass: "Sulfonamide",
    normalDose: "1–2 DS tabs q12h (oral); 15–20 mg/kg/day TMP IV divided q6–8h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "1 DS tab q12h or 50% of IV dose",
    eGFR15_29: "1 DS tab q24h or 50% of IV dose q24h",
    eGFRBelow15: "Avoid for routine therapy; if PCP treatment: 50% dose + TDM",
    notes: "Trimethoprim raises serum creatinine by blocking tubular secretion (not true nephrotoxicity). Hyperkalemia risk at high doses. Sulfonamide crystals in concentrated urine.",
  },
  // ── Nitrofurans ──
  {
    drug: "Nitrofurantoin",
    drugClass: "Nitrofuran",
    normalDose: "100 mg q12h (oral)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Avoid",
    eGFR15_29: "Avoid",
    eGFRBelow15: "Contraindicated",
    notes: "Contraindicated if CrCl <30 — inadequate urinary concentration and risk of peripheral neuropathy. Safe for uncomplicated UTI only.",
  },
  // ── Polymyxins ──
  {
    drug: "Colistin (Polymyxin E)",
    drugClass: "Polymyxin",
    normalDose: "Loading 9 MU, then 4.5 MU q12h",
    eGFR60_89: "4.5 MU q12h",
    eGFR45_59: "4.5 MU q12h",
    eGFR30_44: "3.5 MU q12h",
    eGFR15_29: "3 MU q12h",
    eGFRBelow15: "2.25 MU q12h (or per local nomogram)",
    notes: "Significant nephrotoxicity. Use as last resort. Loading dose same regardless of renal function.",
  },
  // ── Tetracyclines ──
  {
    drug: "Doxycycline",
    drugClass: "Tetracycline",
    normalDose: "100 mg q12h (oral/IV)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Hepatic clearance — preferred tetracycline in renal impairment (unlike tetracycline HCl which is CI).",
  },
  // ── Macrolides ──
  {
    drug: "Azithromycin",
    drugClass: "Macrolide",
    normalDose: "500 mg day 1, then 250 mg days 2–5",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Hepatic clearance — no renal adjustment needed. Caution with QT prolongation.",
  },
  {
    drug: "Clarithromycin",
    drugClass: "Macrolide",
    normalDose: "250–500 mg q12h (oral/IV)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "250–500 mg q24h (reduce 50%)",
    eGFRBelow15: "250–500 mg q24h (reduce 50%)",
    notes: "Reduce dose by 50% if CrCl <30. Potent CYP3A4 inhibitor — check drug interactions. QT prolongation.",
  },
  // ── Antivirals ──
  {
    drug: "Acyclovir (IV)",
    drugClass: "Antiviral",
    normalDose: "5–10 mg/kg q8h (IV)",
    eGFR60_89: "5–10 mg/kg q8h",
    eGFR45_59: "5–10 mg/kg q12h",
    eGFR30_44: "5–10 mg/kg q12–24h",
    eGFR15_29: "2.5–5 mg/kg q24h",
    eGFRBelow15: "2.5 mg/kg q24h (post-dialysis)",
    notes: "Neurotoxic in renal failure (hallucinations, agitation). Ensure adequate hydration. Dose reduction essential.",
  },
  {
    drug: "Valacyclovir",
    drugClass: "Antiviral",
    normalDose: "500 mg–1 g q8h (oral)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "500 mg–1 g q12–24h",
    eGFR15_29: "500 mg–1 g q24h",
    eGFRBelow15: "500 mg q24–48h",
    notes: "Prodrug of acyclovir. Risk of neurotoxicity in CKD (TMA-like syndrome).",
  },
  {
    drug: "Ganciclovir (IV)",
    drugClass: "Antiviral",
    normalDose: "5 mg/kg q12h",
    eGFR60_89: "5 mg/kg q12h",
    eGFR45_59: "2.5 mg/kg q12h",
    eGFR30_44: "2.5 mg/kg q24h",
    eGFR15_29: "1.25 mg/kg q24h",
    eGFRBelow15: "1.25 mg/kg 3×/week post-dialysis",
    notes: "Myelosuppressive. TDM recommended in CKD. Dose post-dialysis.",
  },
  {
    drug: "Valganciclovir",
    drugClass: "Antiviral",
    normalDose: "900 mg q12h (oral)",
    eGFR60_89: "900 mg q12h",
    eGFR45_59: "450 mg q12h",
    eGFR30_44: "450 mg q24h",
    eGFR15_29: "450 mg q48h",
    eGFRBelow15: "450 mg 2×/week post-dialysis",
    notes: "Prodrug of ganciclovir. Strict dose adjustment per CrCl. Monitor CBC.",
  },
  {
    drug: "Oseltamivir",
    drugClass: "Antiviral",
    normalDose: "75 mg q12h (oral) — 5 days",
    eGFR60_89: "75 mg q12h",
    eGFR45_59: "75 mg q12h",
    eGFR30_44: "75 mg q24h",
    eGFR15_29: "75 mg q24h",
    eGFRBelow15: "75 mg single dose, then 75 mg q24h for ESRD (per pandemic protocol)",
    notes: "Reduce frequency for CrCl <30.",
  },
  // ── Antifungals ──
  {
    drug: "Fluconazole",
    drugClass: "Antifungal (Azole)",
    normalDose: "Loading 400–800 mg, then 200–400 mg q24h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "50% of maintenance dose q24h",
    eGFR15_29: "50% of maintenance dose q24h",
    eGFRBelow15: "50% of maintenance dose q24h (dose post-dialysis)",
    notes: "Primarily renal clearance. Reduce maintenance dose by 50% if CrCl <50. Loading dose unchanged.",
  },
  {
    drug: "Voriconazole (IV)",
    drugClass: "Antifungal (Azole)",
    normalDose: "Loading 6 mg/kg q12h × 2, then 4 mg/kg q12h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "IV: avoid (cyclodextrin vehicle accumulates); use oral",
    eGFR15_29: "IV: contraindicated; use oral",
    eGFRBelow15: "IV: contraindicated; use oral",
    notes: "IV formulation contains sulfobutylether-β-cyclodextrin which accumulates in renal failure. Switch to oral if CrCl <50. TDM recommended (trough 1–5.5).",
  },
  {
    drug: "Amphotericin B (Deoxycholate)",
    drugClass: "Antifungal (Polyene)",
    normalDose: "0.5–1 mg/kg q24h",
    eGFR60_89: "Monitor Cr",
    eGFR45_59: "Monitor Cr",
    eGFR30_44: "Monitor Cr",
    eGFR15_29: "Monitor Cr",
    eGFRBelow15: "Monitor Cr",
    notes: "Most nephrotoxic antifungal. Liposomal formulations strongly preferred in any renal impairment. Hydrate and monitor K+, Mg++.",
  },
  // ── Antimycobacterials ──
  {
    drug: "Rifampicin",
    drugClass: "Antimycobacterial",
    normalDose: "450–600 mg q24h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "No adjustment",
    notes: "Hepatic clearance — no renal dose adjustment. Potent CYP450 inducer — major drug interactions.",
  },
  {
    drug: "Isoniazid",
    drugClass: "Antimycobacterial",
    normalDose: "5 mg/kg (max 300 mg) q24h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "No adjustment",
    eGFRBelow15: "200–300 mg q24h (reduce dose)",
    notes: "Hepatic acetylator status determines metabolism. Peripheral neuropathy risk — give pyridoxine. Reduce dose in ESRD.",
  },
  {
    drug: "Pyrazinamide",
    drugClass: "Antimycobacterial",
    normalDose: "20–25 mg/kg q24h",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "20–25 mg/kg 3×/week (after dialysis)",
    eGFRBelow15: "20–25 mg/kg 3×/week (after dialysis)",
    notes: "Hepatic and renal clearance. Reduce frequency in ESRD. Hepatotoxic.",
  },
  {
    drug: "Ethambutol",
    drugClass: "Antimycobacterial",
    normalDose: "15–20 mg/kg q24h",
    eGFR60_89: "15–20 mg/kg q24h",
    eGFR45_59: "15–20 mg/kg q24–36h",
    eGFR30_44: "15–20 mg/kg q36–48h",
    eGFR15_29: "15–20 mg/kg q48h",
    eGFRBelow15: "15–20 mg/kg 3×/week (after dialysis) or 5–7.5 mg/kg q24h",
    notes: "Primarily renal clearance. Optic neuritis risk — monitor visual acuity. Dose reduction essential.",
  },
];
