import type { DoseEntry } from "./RenalDosing";

export const ANTICOAGULANTS_DATA: DoseEntry[] = [
  // ═══════ NOACs / DOACs ═══════
  {
    drug: "Apixaban",
    drugClass: "NOAC (Factor Xa inhibitor)",
    normalDose: "5 mg BID (AF); 10 mg BID ×7d then 5 mg BID (VTE)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment (5 mg BID); 2.5 mg BID if ≥2 of: age ≥80, wt ≤60 kg, Cr ≥1.5",
    eGFR15_29: "2.5 mg BID (AF)",
    eGFRBelow15: "Use with caution / avoid; limited data, may use 2.5 mg BID in HD per US label",
    notes: "~27% renal excretion. Preferred NOAC in advanced CKD. Avoid with strong dual CYP3A4/P-gp inhibitors or inducers.",
  },
  {
    drug: "Rivaroxaban",
    drugClass: "NOAC (Factor Xa inhibitor)",
    normalDose: "20 mg OD (AF, with food); 15 mg BID ×21d then 20 mg OD (VTE)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "15 mg OD (AF)",
    eGFR30_44: "15 mg OD (AF)",
    eGFR15_29: "15 mg OD (AF) — use with caution",
    eGFRBelow15: "Avoid",
    notes: "~33% active renal excretion. Take with evening meal for 15/20 mg doses. Avoid in CrCl <15.",
  },
  {
    drug: "Edoxaban",
    drugClass: "NOAC (Factor Xa inhibitor)",
    normalDose: "60 mg OD",
    eGFR60_89: "60 mg OD",
    eGFR45_59: "30 mg OD",
    eGFR30_44: "30 mg OD",
    eGFR15_29: "30 mg OD",
    eGFRBelow15: "Avoid",
    notes: "Do NOT use if CrCl >95 mL/min (reduced efficacy in AF). Reduce to 30 mg if CrCl 15–50, wt ≤60 kg, or with P-gp inhibitors.",
  },
  {
    drug: "Dabigatran",
    drugClass: "NOAC (Direct thrombin inhibitor)",
    normalDose: "150 mg BID (AF)",
    eGFR60_89: "150 mg BID",
    eGFR45_59: "150 mg BID",
    eGFR30_44: "150 mg BID (consider 110 mg BID if high bleeding risk; 75 mg BID per US label if CrCl 15–30)",
    eGFR15_29: "75 mg BID (US) / Avoid (EU)",
    eGFRBelow15: "Contraindicated",
    notes: "~80% renal excretion — most renally cleared NOAC. Avoid with P-gp inhibitors in CKD. Reversal: idarucizumab.",
  },

  // ═══════ Vitamin K Antagonists ═══════
  {
    drug: "Warfarin",
    drugClass: "Vitamin K antagonist",
    normalDose: "2–10 mg/day, INR-guided (target 2–3)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No dose adjustment; monitor INR closely",
    eGFR15_29: "No dose adjustment; ↑ bleeding risk — monitor INR",
    eGFRBelow15: "No dose adjustment; high bleeding risk, calciphylaxis risk",
    notes: "Hepatic metabolism. CKD increases bleeding and over-anticoagulation risk. Often preferred over NOACs in eGFR <15 / dialysis.",
  },
  {
    drug: "Acenocoumarol",
    drugClass: "Vitamin K antagonist",
    normalDose: "1–8 mg/day, INR-guided",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment; monitor INR",
    eGFR15_29: "No adjustment; ↑ bleeding risk",
    eGFRBelow15: "No adjustment; close INR monitoring",
    notes: "Shorter half-life than warfarin. Same INR target. Bleeding risk rises with declining eGFR.",
  },

  // ═══════ Unfractionated Heparin & LMWH ═══════
  {
    drug: "Unfractionated Heparin (UFH)",
    drugClass: "Heparin (parenteral)",
    normalDose: "80 U/kg bolus then 18 U/kg/h IV (VTE/ACS), aPTT-guided",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment — aPTT/anti-Xa guided",
    eGFR15_29: "No adjustment — preferred over LMWH; aPTT monitoring",
    eGFRBelow15: "No adjustment — preferred parenteral anticoagulant in severe CKD/HD",
    notes: "Reticuloendothelial clearance — not renally eliminated. Preferred over LMWH if eGFR <30. Monitor aPTT 1.5–2.5× control or anti-Xa 0.3–0.7. HIT risk.",
  },
  {
    drug: "Enoxaparin",
    drugClass: "LMWH",
    normalDose: "1 mg/kg SC Q12h (treatment) or 40 mg SC OD (prophylaxis)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment; consider anti-Xa monitoring",
    eGFR15_29: "Treatment: 1 mg/kg SC Q24h; Prophylaxis: 30 mg SC OD",
    eGFRBelow15: "Avoid — use UFH instead",
    notes: "Renal accumulation → bleeding risk in CKD. Peak anti-Xa monitoring recommended in CKD, obesity, pregnancy.",
  },
  {
    drug: "Dalteparin",
    drugClass: "LMWH",
    normalDose: "200 IU/kg SC OD (VTE) or 100 IU/kg BID; 5000 IU OD (prophylaxis)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment; anti-Xa monitoring advised",
    eGFR15_29: "Use with caution; anti-Xa monitoring",
    eGFRBelow15: "Avoid — use UFH",
    notes: "Less renal accumulation than enoxaparin; preferred LMWH in CKD when LMWH must be used. Still monitor anti-Xa.",
  },
  {
    drug: "Tinzaparin",
    drugClass: "LMWH",
    normalDose: "175 IU/kg SC OD",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "No adjustment",
    eGFR15_29: "Use with caution; anti-Xa monitoring",
    eGFRBelow15: "Avoid",
    notes: "Less bioaccumulation in moderate CKD vs enoxaparin (IRIS trial cautioned in elderly CKD). Monitor anti-Xa.",
  },
  {
    drug: "Fondaparinux",
    drugClass: "Synthetic pentasaccharide (anti-Xa)",
    normalDose: "2.5 mg SC OD (prophylaxis); 5–10 mg SC OD (treatment, by weight)",
    eGFR60_89: "No adjustment",
    eGFR45_59: "No adjustment",
    eGFR30_44: "Use with caution; consider dose reduction",
    eGFR15_29: "Contraindicated (treatment); 1.5 mg OD if prophylaxis with caution",
    eGFRBelow15: "Contraindicated",
    notes: "Almost entirely renally cleared. No antidote. Avoid in CrCl <30 for treatment doses.",
  },
];
